{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: {{ template "dps-template.name" . }}-frontend
    {{- include "dps-template.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "dps-template.name" . }}-frontend
    {{- include "dps-template.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  externalTrafficPolicy: Local
  type: LoadBalancer
{{- end }}