{{- if .Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dps-template.name" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ template "dps-template.name" . }}-frontend
    {{- include "dps-template.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "dps-template.name" . }}-frontend
      {{- include "dps-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    labels:
      app.kubernetes.io/name: {{ template "dps-template.name" . }}-frontend
      {{- include "dps-template.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: frontend-app
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
            - name: PORT
              value: "8000"
        ports:
            - containerPort: 8000
        resources:
          requests:
            memory: "512M"
            cpu: "125m"
          limits:
            memory: "1G"
            cpu: "250m"
{{- end }}