---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend
  target:
    name: ghcr-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson 
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: dockerconfigjson
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clouddns-dns01-sa
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend
  target:
    name: clouddns-dns01-sa
    creationPolicy: Owner
  data:
    - secretKey: dns-sa-keyfile.json
      remoteRef:
        key: dns-sa-keyfile-json