apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: ${{values.lifecycle | dump}}
  owner: ${{values.appGroup | dump}}
metadata:
  name: ${{values.component_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}

  tags:
    - springboot
    - postgres
    - react