apiVersion: dps.cluster/v1alpha1
kind: SQLClaim
metadata:
  name: NAME
spec:
  id: NAME
  compositionSelector:
    matchLabels:
      provider: local-k8s
      db: postgresql
  parameters:
    version: "13.4"
    size: small
    namespace: NAMESPACE
  writeConnectionSecretToRef:
    name: NAME
