apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: NAME
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend          
  target:                                                             
    name: SECRET_NAME 
  data:                                                       
  - secretKey: name
    remoteRef:
      key: db-password