{{- if or (.Values.db.enabled.crossplane.google) (.Values.db.enabled.crossplane.aws) (.Values.db.enabled.crossplane.azure) }}
---

apiVersion: dps.cluster/v1alpha1
kind: SQLClaim
metadata:
  annotations:
    "helm.sh/hook-weight": "-10"
  name: {{ template "dps-template.name" . }}
spec:
  id: {{ .Values.db.id }}
  compositionSelector:
    matchLabels:
      {{- if .Values.db.enabled.crossplane.google }}
      provider: google-official
      {{- end }}
      {{- if .Values.db.enabled.crossplane.azure }}
      provider: azure-official
      {{- end }}
      {{- if .Values.db.enabled.crossplane.aws }}
      provider: aws-official
      {{- end }}
      db: postgresql
  parameters:
    {{- if or (.Values.db.enabled.crossplane.azure) (.Values.db.enabled.crossplane.google) }}
    version: "11"
    {{- end }}
    {{- if .Values.db.enabled.crossplane.aws }}
    version: "15.3"
    {{- end }}
    size: {{ .Values.db.size }}
    {{- if .Values.db.enabled.crossplane.aws }}
    providerName: {{ .Values.db.providerName }}
    {{- end }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.db.id }}-password
  annotations:
    "helm.sh/hook-weight": "-10"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend
  target:
    name: {{ .Values.db.id }}-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: db-password

{{- end }}
