---

apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: {{ template "dps-template.name" . }}
    {{- include "dps-template.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ template "dps-template.name" . }}
    {{- include "dps-template.selectorLabels" . | nindent 4 }}