apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: CONTEXT
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    targetRevision: HEAD
    path: deployment/app-dev/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
metedata:
  name: backend-dev
