---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: my-db
spec:
  forProvider:
    region: eu-central-1
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: my-db-a
  labels:
    db: my-db
    zone: eu-central-1a
spec:
  forProvider:
    region: eu-central-1
    availabilityZone: eu-central-1a
    cidrBlock: 10.0.0.0/24
    vpcIdRef:
      name: my-db

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: my-db-b
  labels:
    db: my-db
    zone: eu-central-1b
spec:
  forProvider:
    region: eu-central-1
    availabilityZone: eu-central-1b
    cidrBlock: 10.0.1.0/24
    vpcIdRef:
      name: my-db

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: my-db-c
  labels:
    db: my-db
    zone: eu-central-1c
spec:
  forProvider:
    region: eu-central-1
    availabilityZone: eu-central-1c
    cidrBlock: 10.0.2.0/24
    vpcIdRef:
      name: my-db

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: my-db
spec:
  forProvider:
    region: eu-central-1
    vpcIdRef:
      name: my-db

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: my-db
spec:
  forProvider:
    region: eu-central-1
    vpcIdRef:
      name: my-db
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: my-db
    associations:
    - subnetIdSelector:
        matchLabels:
          db: my-db

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: my-db
spec:
  forProvider:
    description: Security group
    groupName: dot
    region: eu-central-1
    vpcIdRef:
      name: my-db
    ingress:
    - fromPort: 5432
      toPort: 5432
      ipProtocol: tcp
      ipRanges:
      - cidrIp: "0.0.0.0/0"

---

apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: my-db
spec:
  forProvider:
    region: eu-central-1
    dbSubnetGroupNameRef:
      name: my-db
    vpcSecurityGroupIDRefs:
    - name: my-db
    instanceClass: db.m5.large
    masterUsername: masteruser
    engine: postgres
    engineVersion: "14.1"
    skipFinalSnapshot: true
    publiclyAccessible: true
    allocatedStorage: 200
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: my-db-sql
