replicas: 2

image:
  repository: "ghcr.io/digitalproductschool/batch17--react-demo/backend"
  pullPolicy: Always
  tag: "e48b080"

imagePullSecrets: 
  - name: ghcr-credentials


podSecurityContext: 
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"
  seccompProfile:
    type: "RuntimeDefault"

securityContext: 
  capabilities:
    drop: ["ALL"]
  allowPrivilegeEscalation: false


db:
  id: "aws-pg-test"
  enabled:
    crossplane:
      google: false
      aws: false
      azure: false
  size: "small"

ingress:
  host: "test.dpschool.app"
  className: nginx
tls:
  enabled: false
  


