replicas: 2
backend:
  enabled: true
  image:
    repository: ""
    tag: ""
frontend:
  enabled: "true"
  image:
    repository: "ghcr.io/digitalproductschool/dps-template/frontend"
    tag: "1.0.5"
image:
  pullPolicy: Always
imagePullSecrets:
  - name: ghcr-credentials
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"
  seccompProfile:
    type: "RuntimeDefault"
securityContext:
  capabilities:
    drop: ["ALL"]
  allowPrivilegeEscalation: false
db:
  id: ""
  enabled:
    crossplane:
      google: false
      aws: false
      azure: false
  size: ""
  providerName: ""
ingress:
  host: "dps-template.dpschool.app"
  className: nginx
tls:
  enabled: true
