name: Create Backend with postgreSQL instance
run-name: backend-postgres
on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        description: "Environment to deploy app to ( prod, dev )"
      provider:
        required: true
        description: "The Cloud Provider"
        default: aws-official
      size:
        required: true
        description: "Database size (small, medium, large)"
        default: small
      account:
        required: true
        description: "The team's account"
jobs:
  deploy-backend-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Context Variable
        id: context_var
        run: |
          echo "CONTEXT=backend" >> "$GITHUB_ENV"

      - name: Variables
        id: vars
        run: |
          echo "VERSION=1.0.${{ github.run_number }}" >> "$GITHUB_ENV"
          echo "IMAGE=ghcr.io/digitalproductschool/${{ github.event.repository.name }}/${{ env.CONTEXT }}" >> "$GITHUB_ENV"

      - name: Setup pack
        id: setup-pack
        uses: buildpacks/github-actions/setup-pack@v5.1.0
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build image and push to GitHub Container Registry
        id: package
        run: |
          #!/usr/bin/env bash
          pack build --path ${DIR} --builder paketobuildpacks/builder:base --publish ${REPO}:${TAG} -e BP_JVM_VERSION=17
        shell: bash
        env:
          REPO: ${{ env.IMAGE }}
          TAG: ${{ env.VERSION }}
          DIR: ./${{ env.CONTEXT }}
      
      - name: Adjust env
        run: |
          if [ "${{ inputs.env }}" == "development" ]; then
              ENV="dev"
          elif [ "${{ inputs.env }}" == "production" ]; then
              ENV="prod"
          fi
          echo "ENV=$ENV" >> "$GITHUB_ENV"
      
      - name: Create Argo App
        run: |
          chmod +x deployment/scripts/create-argo-app.sh
          ./deployment/scripts/create-argo-app.sh  ${{ env.ENV }} ${{ env.CONTEXT }} ${{ github.event.repository.name }}

      - name: Update Helm
        run: |
          chmod +x deployment/scripts/update-helm-values.sh
          ./deployment/scripts/update-helm-values.sh ${{ env.VERSION }} ${{ env.IMAGE }}  ${{ inputs.provider }} ${{ env.ENV }} ${{ inputs.size }} ${{ inputs.account }} ${{ env.CONTEXT }} ${{ github.event.repository.name }}

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy ${{ env.CONTEXT }} to ${{ env.ENV }} 🤖"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_ACTIONS_BOT_ACCESS_TOKEN}}
          branch: ${{ github.ref }}
