name: Apply custom domain

on:
  workflow_dispatch:
    secrets:
      GCP_ACTIONS_SA:
        required: true
      GCP_CLUSTER_NAME_PROD:
        required: true
      GCP_CLUSTER_NAME_DEV:
        required: true
      GCP_PROJECT:
        required: true
      TF_DNS_SA:
        required: true
env:
  zone: europe-west2

jobs:
  # Declare team name var 
  subdomain-var:
    name: Declare team name var
    runs-on: ubuntu-latest
    outputs:
      subdomain: ${{ steps.subdomain.outputs.SUBDOMAIN }}
    steps:
      - name: Declare subdomain var based on team name extracted from the git repo
        id: subdomain
        shell: bash
        env: 
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          repo=${REPO_NAME}
          echo "SUBDOMAIN=${repo##*--}" >> $GITHUB_OUTPUT

  apply-custom-domain:
    name: Apply a custom domain
    needs: subdomain-var
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GCP_ACTIONS_SA }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # Connect to prod cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ secrets.GCP_CLUSTER_NAME_PROD }}
          location: ${{ env.zone }}
          credentials: ${{ secrets.GCP_ACTIONS_SA }}

      - name: Update ingress file
        run: |
          sed -i 's|<SUBDOMAIN>|${{needs.subdomain-var.outputs.subdomain}}|' $GITHUB_WORKSPACE/${{ inputs.context }}/ingress.yaml
          sed -i 's|<ENV>|prod|' $GITHUB_WORKSPACE/${{ inputs.context }}/ingress.yaml

      - name: Kubectl apply
        run: kubectl apply -n ${{ github.event.repository.name }} -f ${{ inputs.context }}/ingress.yaml