name: Frontend Initialization 

on:
  workflow_dispatch:

jobs:
# Build and deploy frontend in prod env
  build-frontend:
    uses: ./.github/workflows/build-and-deploy-frontend.yml
    with:
      context: ./frontend
      image-name: frontend
      deployment-name: frontend-deployment
      username: ${{ github.actor }}
      env: prod
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      GCP_ACTIONS_SA: ${{ secrets.GCP_ACTIONS_SA }}
      GCP_CLUSTER_NAME_PROD: ${{ secrets.GCP_CLUSTER_NAME_PROD }}
      GCP_CLUSTER_NAME_DEV: ${{ secrets.GCP_CLUSTER_NAME_DEV }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

# Declare subdomain var 
  subdomain-var:
    name: Declare subdomain var
    runs-on: ubuntu-latest
    outputs:
      subdomain: ${{ steps.subdomain.outputs.SUBDOMAIN }}
    steps:
      - name: Declare subdomain var based on team name extracted from the git repo
        id: subdomain
        shell: bash
        env: 
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          repo=${REPO_NAME}
          echo "SUBDOMAIN=${repo##*--}" >> $GITHUB_OUTPUT

# Set up a ingress for prod env 
  setup-ingress: 
    name: Create an ingress frontend in prod env
    needs: [ subdomain-var, build-frontend]
    uses: ./.github/workflows/create-ingress.yml
    with:
      context: ./frontend
      subdomain: ${{needs.subdomain-var.outputs.subdomain}}
      env: prod
    secrets:
      GCP_ACTIONS_SA: ${{ secrets.GCP_ACTIONS_SA }}
      GCP_CLUSTER_NAME_PROD: ${{ secrets.GCP_CLUSTER_NAME_PROD }}
      GCP_CLUSTER_NAME_DEV: ${{ secrets.GCP_CLUSTER_NAME_DEV }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

  setup-ingress-api: 
    name: Create an ingress backend in prod env
    needs: [ subdomain-var]
    uses: ./.github/workflows/create-ingress.yml
    with:
      context: ./backend
      subdomain: ${{needs.subdomain-var.outputs.subdomain}}
      env: prod
    secrets:
      GCP_ACTIONS_SA: ${{ secrets.GCP_ACTIONS_SA }}
      GCP_CLUSTER_NAME_PROD: ${{ secrets.GCP_CLUSTER_NAME_PROD }}
      GCP_CLUSTER_NAME_DEV: ${{ secrets.GCP_CLUSTER_NAME_DEV }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

  setup-ingress-ai: 
    name: Create an ingress ai in prod env
    needs: [ subdomain-var]
    uses: ./.github/workflows/create-ingress.yml
    with:
      context: ./ai
      subdomain: ${{needs.subdomain-var.outputs.subdomain}}
      env: prod
    secrets:
      GCP_ACTIONS_SA: ${{ secrets.GCP_ACTIONS_SA }}
      GCP_CLUSTER_NAME_PROD: ${{ secrets.GCP_CLUSTER_NAME_PROD }}
      GCP_CLUSTER_NAME_DEV: ${{ secrets.GCP_CLUSTER_NAME_DEV }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

# Set up a subdomain for dev env 
  setup-dev-ingress: 
    name: Create an ingress frontend in dev env
    needs: [ subdomain-var ]
    uses: ./.github/workflows/create-ingress.yml
    with:
      context: ./frontend
      subdomain: dev.${{needs.subdomain-var.outputs.subdomain}}
      env: dev
    secrets:
      GCP_ACTIONS_SA: ${{ secrets.GCP_ACTIONS_SA }}
      GCP_CLUSTER_NAME_PROD: ${{ secrets.GCP_CLUSTER_NAME_PROD }}
      GCP_CLUSTER_NAME_DEV: ${{ secrets.GCP_CLUSTER_NAME_DEV }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

  setup-dev-ingress-api: 
    name: Create an ingress backend in dev env
    needs: [ subdomain-var ]
    uses: ./.github/workflows/create-ingress.yml
    with:
      context: ./backend
      subdomain: dev.${{needs.subdomain-var.outputs.subdomain}}
      env: dev
    secrets:
      GCP_ACTIONS_SA: ${{ secrets.GCP_ACTIONS_SA }}
      GCP_CLUSTER_NAME_PROD: ${{ secrets.GCP_CLUSTER_NAME_PROD }}
      GCP_CLUSTER_NAME_DEV: ${{ secrets.GCP_CLUSTER_NAME_DEV }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

  setup-dev-ingress-ai: 
    name: Create an ingress ai in dev env
    needs: [ subdomain-var ]
    uses: ./.github/workflows/create-ingress.yml
    with:
      context: ./ai
      subdomain: dev.${{needs.subdomain-var.outputs.subdomain}}
      env: dev
    secrets:
      GCP_ACTIONS_SA: ${{ secrets.GCP_ACTIONS_SA }}
      GCP_CLUSTER_NAME_PROD: ${{ secrets.GCP_CLUSTER_NAME_PROD }}
      GCP_CLUSTER_NAME_DEV: ${{ secrets.GCP_CLUSTER_NAME_DEV }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

  get-dev-hostname: 
    name: Get dev hostname
    needs: [ subdomain-var, setup-dev-ingress ]
    uses: ./.github/workflows/get-hostname.yml
    with:
      subdomain: dev.${{needs.subdomain-var.outputs.subdomain}}
      env: dev
    secrets:
      GCP_ACTIONS_SA: ${{ secrets.GCP_ACTIONS_SA }}
      GCP_CLUSTER_NAME_PROD: ${{ secrets.GCP_CLUSTER_NAME_PROD }}
      GCP_CLUSTER_NAME_DEV: ${{ secrets.GCP_CLUSTER_NAME_DEV }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  
  get-prod-hostname: 
    name: Get prod hostname
    needs: [ subdomain-var, setup-ingress]
    uses: ./.github/workflows/get-hostname.yml
    with:
      subdomain: ${{needs.subdomain-var.outputs.subdomain}}
      env: prod
    secrets:
      GCP_ACTIONS_SA: ${{ secrets.GCP_ACTIONS_SA }}
      GCP_CLUSTER_NAME_PROD: ${{ secrets.GCP_CLUSTER_NAME_PROD }}
      GCP_CLUSTER_NAME_DEV: ${{ secrets.GCP_CLUSTER_NAME_DEV }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

