name: Get Hostname
on:
  workflow_call:
    inputs:
      subdomain:
        required: true
        type: string
      env:
        required: true
        type: string
    secrets:
      GCP_ACTIONS_SA:
        required: true
      GCP_CLUSTER_NAME_PROD:
        required: true
      GCP_CLUSTER_NAME_DEV:
        required: true
      GCP_PROJECT:
        required: true

env:
  zone: europe-west2

jobs:
  get-hostname:
    name: Get Hostname
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GCP_ACTIONS_SA }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # Connect to prod cluster if the env is prod 
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        if: inputs.env == 'prod'
        with:
          cluster_name: ${{ secrets.GCP_CLUSTER_NAME_PROD }}
          location: ${{ env.zone }}
          credentials: ${{ secrets.GCP_ACTIONS_SA }}
      
      # Connect to dev cluster if the env is dev
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        if: inputs.env == 'dev'
        with:
          cluster_name: ${{ secrets.GCP_CLUSTER_NAME_DEV }}
          location: ${{ env.zone }}
          credentials: ${{ secrets.GCP_ACTIONS_SA }}

      - name: get Host name
        id: host
        shell: bash
        run: |
          echo "🎉 your hostname is :  $(kubectl get ingress ${{ inputs.subdomain }} -n ${{ github.event.repository.name }} -o jsonpath="{.spec.rules[0].host}")"